version: '3.1'

services:
  app:
    build: .
    ports:
      - 7000:7000
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5000:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data: {}